### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by SemenMartynov** [stakenschneider/validationService#12]
Fix error message and go the task 3.

**Comment by stakenschneider** [comment]
@SemenMartynov f003af2a56eda2e8eb1a60f490f547f244aee53d

**Comment by SemenMartynov** [comment]
Sorry, didn't understand you point) It's not the 3rd task, is it?

**Comment by stakenschneider** [comment]
@SemenMartynov [https://github.com/stakenschneider/validationService/blob/master/Jenkins.jpg](url)

**Comment by stakenschneider** [comment]
@SemenMartynov вы слишком быстро проверили, я уже поменяла)

**Comment by SemenMartynov** [comment]
Good. You need to ask @Ikhoziainov for check after complete this task.

**Comment by kotmakrus** [comment]
okay, i sent him an invite link
