### ISSUE TITLE
Request counter doen't work

### ISSUE THREAD

**Issue by SemenMartynov** [stakenschneider/validationService#8]
`"requestID": "0"`

**Comment by SemenMartynov** [comment]
Now, the counter is always 12345...

**Comment by stakenschneider** [comment]
@SemenMartynov вы же разрешили задать это константой, как и номер ошибки

**Comment by SemenMartynov** [comment]
No, you are wrong.
Check the task here -- https://github.com/SemenMartynov/SPbPU_TRPO_2017/blob/master/Task01.RUS.txt
